version: 2.1
orbs:
  heroku: circleci/heroku@0.0.10
  cypress: cypress-io/cypress@1
workflows:
  test_and_heroku_deploy:
    jobs:
      - cypress/run:
          command: yarn test
      - heroku/deploy-via-git:
          requires:
          - cypress/run